apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wealthy-ingress
spec:
  rules:
  - host: wealthy.roadking.io
    http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: wealthy-backend
              port:
                number: 80
