apiVersion: apps/v1
kind: Deployment
metadata:
  name: wealthy-backend
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: wealthy-backend
  template:
    metadata:
      labels:
        app: wealthy-backend
    spec:
      containers:
      - image: kaa4ever2/wealthy-backend:latest
        name: wealthy-backend
        - containerPort: 80