apiVersion: apps/v1
kind: Deployment
metadata:
  name: wealthy-frontend
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: wealthy-frontend
  template:
    metadata:
      labels:
        app: wealthy-frontend
    spec:
      containers:
      - image: kaa4ever2/wealthy-frontend@sha256:3450a6b16b6e879903b173c7363d567b4d13c2494d4d22ddad281c7c59e981af
        name: wealthy-frontend
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_API_BACKEND
          value: whatisthis