apiVersion: apps/v1
kind: Deployment
metadata:
  name: wealthy-frontend
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: wealthy-frontend
  template:
    metadata:
      labels:
        app: wealthy-frontend
    spec:
      containers:
      - image: kaa4ever2/wealthy-frontend@sha256:abd839aa8cad2d0c8778b99449ed4e821da197fd701f0c5ffd08bd47e6bc0523
        name: wealthy-frontend
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_API_BACKEND
          value: whatisthis