apiVersion: apps/v1
kind: Deployment
metadata:
  name: wealthy-frontend
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: wealthy-frontend
  template:
    metadata:
      labels:
        app: wealthy-frontend
    spec:
      containers:
      - image: kaa4ever2/wealthy-frontend@sha256:6d28d61d3ff3d4530c8c9917273bd384c0e2069706c76d21dbc25274a7cf5bd3
        name: wealthy-frontend
        ports:
        - containerPort: 80