apiVersion: apps/v1
kind: Deployment
metadata:
  name: wealthy-frontend
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: wealthy-frontend
  template:
    metadata:
      labels:
        app: wealthy-frontend
    spec:
      containers:
      - image: kaa4ever2/wealthy-frontend@sha256:f089329d5ca0f12490a671627e01bf58e8ca477ddd4cc0038289033517f75f9e
        name: wealthy-frontend
        ports:
        - containerPort: 80