apiVersion: apps/v1
kind: Deployment
metadata:
  name: wealthy-backend
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: wealthy-backend
  template:
    metadata:
      labels:
        app: wealthy-backend
    spec:
      containers:
      - image: kaa4ever2/wealthy-backend@sha256:a919a9765937b0f51514b973c06d409e9eddc4bcb95f99ccac4b26ed22d4117d
        name: wealthy-backend
        ports:
        - containerPort: 80
        env:
        - name: SQLALCHEMY_DATABASE_URL
          value: "postgresql://postgres:example@wealthy-db/wealthy"
